-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgOijfH4nbumH1m7yf
gkdY/JV6AdLNWSpoKOUz2UjzWJWgCgYIKoZIzj0DAQehRANCAATW0wqpoQdelWQg
U5cNADZr5UKSLiDO+LG1Ze5udV+O4EU1qN+eZwy+AO4chW/2HhSOASZWswsLT0gu
aaGSUjz/
-----END PRIVATE KEY-----