type ReducerType = {
}

const LOGGEDIN_USER_DATA = 'LoginUserData'
const LOGOUT= 'Logout'
const FCM_DEVICE_TOKEN= 'FCMDeviceToken'
const LOGGEDIN_USER_TYPE = 'UserType'
const SHOULD_AUTO_LOGIN = 'ShouldAutoLogin'
const ALL_USER_LOGIN_DATA = 'ALlUserLoginData'
const USER_REMEMBERED_EMAIL = 'Email'
const USER_REMEMBERED_PASSWORD = 'Password'
const LAST_SCREEN = 'LastScreen'
const SCHEDULE_AVAILABILITY = 'ScheduleAvailability'
const PROFILE_DATA = 'ProfileData'
const PROFILE_COMPLETION_DATA = 'ProfileCompletionData'
const RATINGS = 'Ratings'
const NOTIFICATIONS = 'Notifications'
const NOTIFICATION_COUNT = 'NotificationsCount'
const APP_STATE = 'APP_STATE'
const VIDEO_CALL='VIDEO_CALL'
const VIDEO_CALL_DATA='VIDEO_CALL_DATA'

export {
    ReducerType,
    LOGGEDIN_USER_DATA, 
    LOGOUT,
    FCM_DEVICE_TOKEN,
    LOGGEDIN_USER_TYPE,
    SHOULD_AUTO_LOGIN,
    ALL_USER_LOGIN_DATA,
    USER_REMEMBERED_EMAIL,
    USER_REMEMBERED_PASSWORD,
    LAST_SCREEN,
    SCHEDULE_AVAILABILITY,
    PROFILE_DATA,
    PROFILE_COMPLETION_DATA,
    RATINGS,
    NOTIFICATIONS,
    NOTIFICATION_COUNT,
    APP_STATE,
    VIDEO_CALL,
    VIDEO_CALL_DATA
}