export const localimag = {
  //----------------------------------------------by gunjan
  splashlogo: require('../icons/Logo2x.png'),
  logo: require('../icons/logo.png'),
  remembertick: require('../icons/chcek-icon.png'),
  rememberdeactivate: require('../icons/graycheckbox.png'),
  // backarrow: require('../icons/backarrow.png'),
  bellicon: require('../icons/notifications3x.png'),
  profileimg: require('../icons/black-profile-image3x.png'),
  editicon: require('../icons/editicon.png'),
  notifications_sec: require('../icons/notifiva.png'),
  // camera: require('../icons/camera.png'),
  //----------------------------------------------
  account2xIcon: require('../icons/account2x.png'),
  transectionIcon: require('../icons/transection.png'),
  ScheduleartIcon: require('../icons/Schedule-art.png'),
  PricelistIcon: require('../icons/Pricelist.png'),
  appointmentIcon: require('../icons/appointment-art.png'),
  appointmentIcon: require('../icons/appointment-art.png'),
  rightDIcon: require('../icons/rightArrow.png'),
  rightarrow: require('../icons/back-33x.png'),
  p1: require('../icons/download33x.png'),
  user_img: require('../icons/photo-43x.png'),
  notifications: require('../icons/notifications3x.png'),
  searchiocn2: require('../icons/searchiocn2.png'),
  nurse: require('../icons/covid-19-preventing-virus-health-healthcare-workers-quarantine-concept-professional-female-nurse-doctor-blue-scrubs-medical-mask-gloves-writing-down-p3x.png'),
  nurse2: require('../icons/dj31p7w93x.png'),
  starrating: require('../icons/Path19633x.png'),
  Physiotherapist: require('../icons/0c3ib4og3x.png'),
  NurseAssistant: require('../icons/02fkwh543x.png'),
  Babysitter: require('../icons/ml0zextx3x.png'),
  InstantVideoConsultation: require('../icons/healthcare-medical-concept-male-ear-nose-throat-doctor3x.png'),
  HomeVisitConsultation: require('../icons/elderly-doctor-listening-young-patient3x.png'),
  BookaLabTest: require('../icons/woman-working-laborator23x.png'),
  HoptlInstantVideoConsultation: require('../icons/smiling-doctors-with-stethoscope3x.png'),

  Home: require('../icons/Path48753x.png'),
  Appointment: require('../icons/Component14813x.png'),
  Cart: require('../icons/Subtraction223x.png'),
  More: require('../icons/ic_more_horiz_24px3x.png'),

  leftarrow: require('../icons/Vector-1.png'),
  More: require('../icons/ic_more_horiz_24px3x.png'),
  Emptycart: require('../icons/Empty-cart-ic2x.png'),
  Nurse1: require('../icons/photo-73x.png'),

  //26
  p2: require('../icons/photo-13x.png'),
  p3: require('../icons/photo-23x.png'),
  addicon: require('../icons/Group11453x.png'),
  cross: require('../icons/Group10883x.png'),
  cross2: require('../icons/Path19223x.png'),
  search: require('../icons/Component23x.png'),
  search2: require('../icons/Component2023x.png'),
  camera: require('../icons/Path63433x.png'),
  downarrow: require('../icons/back-svg.png'),
  uparrow: require('../icons/up_arrow.png'),
  //28 radhekrishan
  location: require('../icons/Path94313x.png'),
  clock: require('../icons/Path94303x.png'),
  clock_arabic: require('../icons/clocl_arabic.png'),
  clock_arabic_gray: require('../icons/grya_cloc.png'),
  //01-03  radhekrishan
  editpen: require('../icons/Group11713x.png'),
  user2: require('../icons/Group10503x.png'),
  rightarrow: require('../icons/back-33x.png'),
  calender: require('../icons/Union683x.png'),
  calender2: require('../icons/Union723x.png'),
  setting: require('../icons/Component7813x.png'),
  transactionhistory: require('../icons/transactionhistory.png'),
  pricelistmenu: require('../icons/pricelistmenu.png'),
  reviewrating: require('../icons/reviewrating.png'),
  support: require('../icons/Path61473x.png'),
  logout: require('../icons/Export3x.png'),
  logout_opp: require('../icons/loout_opp.png'),
  dots: require('../icons/Group12383x.png'),
  purse: require('../icons/Path58733x.png'),
  //02-03 radhekrishan
  purse: require('../icons/Path58733x.png'),
  //04-03 radhekrishan
  prescription: require('../icons/prescription.png'),
  report: require('../icons/report.png'),
  upload: require("../icons/attachment.png"),
  //05-03 radhekrishan
  bluetick: require('../icons/bluetick.png'),
  graycheckbox: require('../icons/graycheckbox.png'),
  greentick: require('../icons/greentick.png'),
  rocketicon: require('../icons/rocketicon.png'),

  //28 gunjan
  Forgotlogo: require('../icons/rc-logo3x.png'),
  forwardarrow: require('../icons/back-33x.png'),
  needsupportimg: require('../icons/Path51083x.png'),
  backarrow: require('../icons/Vector-1.png'),

  //---02/03 gunjan

  dobimg: require('../icons/date.png'),
  locationcurrent: require('../icons/locationcurrent.png'),
  rightimg: require('../icons/Group1336-22x.png'),
  //--05-03-22 gunjan
  crossimg: require('../icons/Group10883x.png'),
  calendarimg: require('../icons/date.png'),
  arabic_back: require('../icons/next.png'),
  arabic_next: require('../icons/left-arrow.png'),
  arabic_call: require('../icons/arabic_call.png'),
  purse_arbic: require('../icons/arabic_wallet.png'),
  rocket_gray: require('../icons/gry_rocekt.png'),
  play: require('../icons/play.png'),
  pause: require('../icons/pause.png')
};
